name = 'My Game'

modules = [
    './main',
    '@rpgjs/mobile-gui',
    '@rpgjs/default-gui',
    '@rpgjs/gamepad'
]

[start]
    map = 'simplemap'
    graphic = 'hero'
    hitbox = [16, 16]

[inputs.up]
    name = "up"
    repeat = true
    bind = "up"

[inputs.down]
    name = "down"
    repeat = true
    bind = "down"

[inputs.right]
    name = "right"
    repeat = true
    bind = "right"

[inputs.left]
    name = "left"
    repeat = true
    bind = "left"

[inputs.action]
    name = "action"
    bind = ["space", "enter", "click"]

[inputs.back]
    name = "back"
    bind = "escape"